#********************** Makefile for Printer\4208.CPI **********************

inc	=..\..\..\inc
dos	=..\..\..\dos
hinc	=..\..\..\h
msg	=..\..\..\message

#
######################### Dependencies Begin Here ##########################
#

all: 4208.cpi

4208.obj:  4208.asm  $(inc)\copyrigh.inc makefile


4208.cpi:  4208.obj
          link 4208;
          exe2bin 4208 4208.cpi
          del 4208.exe

clean:
	@if exist *.obj del *.obj
	@if exist 4208.cpi del 4208.cpi
