#************************ Makefile for Country.sys ************************

dos	=..\..\dos
lib	=..\..\lib
inc	=..\..\inc

#
######################## Dependencies begin here ##########################
#

all: country.sys

mkcntry.obj: mkcntry.asm mkcntry.inc

mkcntry.exe: mkcntry.obj
	link mkcntry;

country.sys: mkcntry.exe
	mkcntry

clean:
	@if exist *.obj del *.obj
	@if exist country.sys del country.sys
	@if exist mkcntry.exe del mkcntry.exe
