#************************* makefile for messages **************************

country    =usa-ms

#
#######################	dependencies begin here. #########################
#

all: $(country).idx

$(country).idx: $(country).msg

clean:
	@if exist usa-ms.idx del usa-ms.idx
