#************************** makefile for cmd\... ***************************

msg	=..\..\messages
dos	=..\..\dos
inc	=..\..\inc
hinc	=..\..\h

#
#######################	dependencies begin here. #########################
#

all: tree.com

tree.ctl: tree.skl \
    $(msg)\$(COUNTRY).msg \
    makefile

tree.obj: tree.asm \
    makefile \
    treequ.inc

treesysp.obj: treesysp.asm \
    makefile \
    $(inc)\psdata.inc \
    $(inc)\parse.asm

treesysm.obj: treesysm.asm \
    makefile \
    $(inc)\copyrigh.inc \
    $(inc)\versiona.inc \
    $(inc)\sysmsg.inc \
    $(inc)\msgserv.asm \
    tree.ctl \
    tree.cl1 \
    tree.cl2 \
    tree.cla \
    $(inc)\msghan.inc \
    treems.inc

treepar.obj: treepar.asm \
    makefile

tree.com: tree.obj \
    makefile \
    tree.lnk \
    treesysp.obj \
    treesysm.obj \
    treepar.obj
	link @tree.lnk
	exe2bin tree.exe tree.com
	del tree.exe

clean:
	@if exist *.obj del *.obj
	@if exist tree.com del tree.com
	@if exist tree.cl1 del tree.cl1
	@if exist tree.cl2 del tree.cl2
	@if exist tree.cla del tree.cla
	@if exist tree.ctl del tree.ctl
