#************************ makefile for dev\driver ************************

msg	=..\..\messages
dos	=..\..\dos
inc	=..\..\inc
hinc	=..\..\h

#
#######################	dependencies begin here. #########################
#

all: driver.sys

driver.ctl: driver.skl  $(msg)\$(COUNTRY).msg

driver.obj: driver.asm  $(inc)\msbds.inc $(inc)\versiona.inc \
            $(inc)\parse.asm $(inc)\psdata.inc \
            driver.ctl $(inc)\sysmsg.inc $(inc)\msgserv.asm

driver.sys: driver.obj driver.lnk
        link @driver.lnk
        exe2bin driver.exe driver.sys
        del driver.exe

clean:
	@if exist *.obj del *.obj
	@if exist driver.sys del driver.sys
	@if exist driver.cl1 del driver.cl1
	@if exist driver.cl2 del driver.cl2
	@if exist driver.cla del driver.cla
	@if exist driver.ctl del driver.ctl
