#******************** makefile for boot *****************************

msg	=..\messages
dos	=..\dos
inc	=..\inc
hinc	=..\h

#
#################### dependencies begin here ############################
#

all: msboot.bin

boot.cl1: boot.skl \
	$(msg)\$(COUNTRY).MSG \
	makefile

msboot.obj: msboot.asm boot.cl1

msboot.bin: msboot.obj
	link msboot;
	exe2bin msboot.exe msboot.bin
	dbof msboot.bin boot.inc 7c00 200
	copy boot.inc $(inc)
	del boot.inc

clean:
	@if exist *.obj del *.obj
	@if exist msboot.exe del msboot.exe
	@if exist boot.cl1 del boot.cl1
	@if exist msboot.bin del msboot.bin
