#************************** DEV root level Makefile ***********************

make	=nmake

all:
	$(MAKE) -C COUNTRY
	$(MAKE) -C ANSI
	$(MAKE) -C KEYBOARD
	$(MAKE) -C DISPLAY
	$(MAKE) -C PRINTER
	$(MAKE) -C DRIVER
	$(MAKE) -C RAMDRIVE
	$(MAKE) -C SMARTDRV
	$(MAKE) -C XMA2EMS
	$(MAKE) -C VDISK
	$(MAKE) -C XMAEM

clean:
	$(MAKE) -C COUNTRY clean
	$(MAKE) -C ANSI clean
	$(MAKE) -C KEYBOARD clean
	$(MAKE) -C DISPLAY clean
	$(MAKE) -C PRINTER clean
	$(MAKE) -C DRIVER clean
	$(MAKE) -C RAMDRIVE clean
	$(MAKE) -C SMARTDRV clean
	$(MAKE) -C XMA2EMS clean
	$(MAKE) -C VDISK clean
	$(MAKE) -C XMAEM clean
