#************************* Root level Makefile *************************

make	=nmake

all:
	$(MAKE) -C MESSAGES
	$(MAKE) -C MAPPER
	$(MAKE) -C BOOT
	$(MAKE) -C BIOS
	$(MAKE) -C DOS
	$(MAKE) -C CMD
	$(MAKE) -C DEV
	$(MAKE) -C SELECT
	$(MAKE) -C MEMM

clean:
	$(MAKE) -C MESSAGES clean
	$(MAKE) -C MAPPER clean
	$(MAKE) -C BOOT clean
	$(MAKE) -C BIOS clean
	$(MAKE) -C DOS clean
	$(MAKE) -C CMD clean
	$(MAKE) -C DEV clean
	$(MAKE) -C SELECT clean
	$(MAKE) -C MEMM clean
	$(MAKE) -C INC clean
