#************************** CMD Root level Makefile ***********************

make	=nmake

all:
	$(MAKE) -C COMMAND
	$(MAKE) -C ATTRIB
	$(MAKE) -C ASSIGN
	$(MAKE) -C CHKDSK
	$(MAKE) -C DEBUG
	$(MAKE) -C EDLIN
	$(MAKE) -C EXE2BIN
	$(MAKE) -C FIND
	$(MAKE) -C FC
	$(MAKE) -C FORMAT
	$(MAKE) -C JOIN
	$(MAKE) -C MORE
	$(MAKE) -C PRINT
	$(MAKE) -C RECOVER
	$(MAKE) -C SORT
	$(MAKE) -C SUBST
	$(MAKE) -C SYS
	$(MAKE) -C SHARE
	$(MAKE) -C NLSFUNC
	$(MAKE) -C IFSFUNC
	$(MAKE) -C MEM
	$(MAKE) -C FILESYS
	$(MAKE) -C BACKUP
	$(MAKE) -C COMP
	$(MAKE) -C DISKCOMP
	$(MAKE) -C DISKCOPY
	$(MAKE) -C FDISK
	$(MAKE) -C LABEL
	$(MAKE) -C MODE
	$(MAKE) -C RESTORE
	$(MAKE) -C TREE
	$(MAKE) -C REPLACE
	$(MAKE) -C XCOPY
	$(MAKE) -C GRAFTABL
	$(MAKE) -C FASTOPEN
	$(MAKE) -C APPEND
	$(MAKE) -C GRAPHICS
	$(MAKE) -C KEYB

clean:
	$(MAKE) -C COMMAND clean
	$(MAKE) -C ATTRIB clean
	$(MAKE) -C ASSIGN clean
	$(MAKE) -C CHKDSK clean
	$(MAKE) -C DEBUG clean
	$(MAKE) -C EDLIN clean
	$(MAKE) -C EXE2BIN clean
	$(MAKE) -C FIND clean
	$(MAKE) -C FC clean
	$(MAKE) -C FORMAT clean
	$(MAKE) -C JOIN clean
	$(MAKE) -C MORE clean
	$(MAKE) -C PRINT clean
	$(MAKE) -C RECOVER clean
	$(MAKE) -C SORT clean
	$(MAKE) -C SUBST clean
	$(MAKE) -C SYS clean
	$(MAKE) -C SHARE clean
	$(MAKE) -C NLSFUNC clean
	$(MAKE) -C IFSFUNC clean
	$(MAKE) -C MEM clean
	$(MAKE) -C FILESYS clean
	$(MAKE) -C BACKUP clean
	$(MAKE) -C COMP clean
	$(MAKE) -C DISKCOMP clean
	$(MAKE) -C DISKCOPY clean
	$(MAKE) -C FDISK clean
	$(MAKE) -C LABEL clean
	$(MAKE) -C MODE clean
	$(MAKE) -C RESTORE clean
	$(MAKE) -C TREE clean
	$(MAKE) -C REPLACE clean
	$(MAKE) -C XCOPY clean
	$(MAKE) -C GRAFTABL clean
	$(MAKE) -C FASTOPEN clean
	$(MAKE) -C APPEND clean
	$(MAKE) -C GRAPHICS clean
	$(MAKE) -C KEYB clean
