#************************** CMD Root level Makefile ***********************

make	=nmake

all:
	cd command
	$(make)
	cd ..\attrib
	$(make)
	cd ..\assign
	$(make)
	cd ..\chkdsk
	$(make)
	cd ..\debug
	$(make)
	cd ..\edlin
	$(make)
	cd ..\exe2bin
	$(make)
	cd ..\find
	$(make)
	cd ..\fc
	$(make)
	cd ..\format
	$(make)
	cd ..\join
	$(make)
	cd ..\more
	$(make)
	cd ..\print
	$(make)
	cd ..\recover
	$(make)
	cd ..\sort
	$(make)
	cd ..\subst
	$(make)
	cd ..\sys
	$(make)
	cd ..\share
	$(make)
	cd ..\nlsfunc
	$(make)
	cd ..\ifsfunc
	$(make)
	cd ..\mem
	$(make)
	cd ..\filesys
	$(make)
	cd ..\backup
	$(make)
	cd ..\comp
	$(make)
	cd ..\diskcomp
	$(make)
	cd ..\diskcopy
	$(make)
	cd ..\fdisk
	$(make)
	cd ..\label
	$(make)
	cd ..\mode
	$(make)
	cd ..\restore
	$(make)
	cd ..\tree
	$(make)
	cd ..\replace
	$(make)
	cd ..\xcopy
	$(make)
	cd ..\graftabl
	$(make)
	cd ..\fastopen
	$(make)
	cd ..\append
	$(make)
	cd ..\graphics
	$(make)
	cd ..\keyb
	$(make)
	cd ..

clean:
	cd command
	$(make) clean
	cd ..\attrib
	$(make) clean
	cd ..\assign
	$(make) clean
	cd ..\chkdsk
	$(make) clean
	cd ..\debug
	$(make) clean
	cd ..\edlin
	$(make) clean
	cd ..\exe2bin
	$(make) clean
	cd ..\find
	$(make) clean
	cd ..\fc
	$(make) clean
	cd ..\format
	$(make) clean
	cd ..\join
	$(make) clean
	cd ..\more
	$(make) clean
	cd ..\print
	$(make) clean
	cd ..\recover
	$(make) clean
	cd ..\sort
	$(make) clean
	cd ..\subst
	$(make) clean
	cd ..\sys
	$(make) clean
	cd ..\share
	$(make) clean
	cd ..\nlsfunc
	$(make) clean
	cd ..\ifsfunc
	$(make) clean
	cd ..\mem
	$(make) clean
	cd ..\filesys
	$(make) clean
	cd ..\backup
	$(make) clean
	cd ..\comp
	$(make) clean
	cd ..\diskcomp
	$(make) clean
	cd ..\diskcopy
	$(make) clean
	cd ..\fdisk
	$(make) clean
	cd ..\label
	$(make) clean
	cd ..\mode
	$(make) clean
	cd ..\restore
	$(make) clean
	cd ..\tree
	$(make) clean
	cd ..\replace
	$(make) clean
	cd ..\xcopy
	$(make) clean
	cd ..\graftabl
	$(make) clean
	cd ..\fastopen
	$(make) clean
	cd ..\append
	$(make) clean
	cd ..\graphics
	$(make) clean
	cd ..\keyb
	$(make) clean
	cd ..
