#************************* Root level Makefile *************************

make	=nmake

all:
	cd emm
	$(make)
	cd ..\memm
	$(make)
	cd ..

clean:
	cd emm
	$(make) clean
	cd ..\memm
	$(make) clean
	cd ..
