#************************** makefile for cmd\backup ***************************

cflags	= -AS -Od -Zp $(extcsw)
msg	=..\..\messages
dos	=..\..\dos
inc	=..\..\inc
hinc	=..\..\h
map	=..\..\mapper
here	=..\cmd\backup

#
#######################	dependencies begin here. #########################
#

all: backup.com

$(map)\mapper.lib:
	cd $(map)
	nmake
	cd $(here)

_parse.obj:	_parse.asm			\
		$(inc)\parse.asm		\
		$(inc)\psdata.inc		\
		makefile

backup.ctl:	backup.skl			\
		$(msg)\$(COUNTRY).MSG		

_msgret.obj:	_msgret.asm			\
		backup.ctl			\
		$(inc)\msgserv.asm		\
		$(inc)\sysmsg.inc		\
		$(inc)\versiona.inc		\
		$(inc)\copyrigh.inc		\
		makefile

backup.obj:  backup.c  backpars.h backup.h  makefile	\
	     $(hinc)\doscalls.h

backup.com: backup.obj _parse.obj _msgret.obj		\
	    $(map)\mapper.lib $(inc)\comsubs.lib
	link /NOE backup + _parse + _msgret,,,$(map)\mapper + $(inc)\comsubs;
	convert backup.exe backup.com
	del backup.exe

clean:
	@if exist *.obj del *.obj
	@if exist backup.com del backup.com
	@if exist backup.cl1 del backup.cl1
	@if exist backup.cl2 del backup.cl2
	@if exist backup.cla del backup.cla
	@if exist backup.ctl del backup.ctl
	@if exist backup.map del backup.map
